# Generated by Django 6.0.3 on 2026-04-08 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Designation', models.CharField(max_length=100)),
                ('DateofJoining', models.DateField()),
                ('Contact', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
                ('Dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=255)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
